Fantasy/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('reviews/', include('reviews.urls')),
    path('admin/', admin.site.urls),
    
]

reviews/urls.py
from django.urls import path

from . import views

app_name = 'reviews'
urlpatterns = [
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('', views.PostListView.as_view(), name='index'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('category/', views.CategoryListView.as_view(), name='category'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='single'),
    
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('themes/', views.themes, name='themes'),
    path('themes/magic/', views.magic, name='magic'),
    path('themes/chars/', views.chars, name='chars'),
    path('themes/games/', views.games, name='games'),
]

reviews/models.py
from django.db import models
from django.conf import settings
from datetime import datetime
from django.urls import reverse

class Post(models.Model):
    name = models.CharField(max_length=255)
    text = models.CharField(max_length=255)
    poster_url = models.URLField(max_length=200, null=True)
    date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return f'{self.name}'

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.now, blank=True)
    def __str__(self):
        return f'"{self.text}" - {self.author.username}'

class Category(models.Model):
    name = models.CharField(max_length=255)
    desc = models.CharField(max_length=255)
    group = models.ManyToManyField(Post)

    def __str__(self):
        return f'{self.name}'

staticpages/models.py
from django.db import models

# Create your models here.

reviews/forms.py
from django.forms import ModelForm
from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'name',
            'text',
            'poster_url',
        ]
        labels = {
            'name': 'Título',
            'text': 'Texto',
            'poster_url': 'URL da Imagem',
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Resenha',
        }

reviews/views.py
from django.shortcuts import render
from .models import Post
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment, Category
from .forms import PostForm, CommentForm
from django.views import generic

# Create your views here.
class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'reviews/detail.html'

class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = 'reviews/single.html'


class PostListView(generic.ListView):
    model = Post
    template_name = 'reviews/index.html'

class PostCreateView(generic.CreateView):
    model = Post
    fields = [
        'name',
        'text',
        'poster_url',
    ]
    template_name = 'reviews/create.html'
    success_url = '/reviews'


class PostUpdateView(generic.UpdateView):
    model = Post
    fields = [
        'name',
        'text',
        'poster_url',
    ]
    template_name = 'reviews/update.html'
    success_url = '/reviews'


class PostDeleteView(generic.DeleteView):
    model = Post
    template_name = 'reviews/delete.html'
    success_url = '/reviews'


def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('reviews:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'reviews/comment.html', context)

class CategoryListView(generic.ListView):
    model = Category
    template_name = 'reviews/category.html'

staticpages/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

def themes(request):
    context = {}
    return render(request, 'staticpages/themes.html', context)

def magic(request):
    context = {}
    return render(request, 'staticpages/magic.html', context)

def chars(request):
    context = {}
    return render(request, 'staticpages/chars.html', context)

def games(request):
    context = {}
    return render(request, 'staticpages/games.html', context)

reviews/templates/reviews/category.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias referentes às postagens</h2>

<section>
    {% for category in category_list %}
    <hr>
    <article>
        <header>
            <a href="{% url 'reviews:single' category.id %}"> {{category.name}} </a>
        </header>
        <div>
            {% for post in category.group.all %}
            <div>
                <a href="{% url 'reviews:detail' post.id %}"> {{ post.name}}</a>
                
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}

    
</section>

{% endblock content %}

reviews/templates/reviews/comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentários de {{ comment.name }} </h2>

<form action="{% url 'reviews:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar comentário</button>
</form>

<p><a href="{% url 'reviews:detail' post.id %}">Voltar para a página da postagem</a></p>
{% endblock content %}

reviews/templates/reviews/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Review</h2>
<form method="POST" action="{% url 'reviews:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

reviews/templates/reviews/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'reviews:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar a postagem? "{{ post.name }} ({{ post.text }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

reviews/templates/reviews/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.name }} ({{ post.text }}
{% endblock title %}

{% block content %}
<h2>Detalhes da Review: {{ post.name }} </h2>



<section>
    <img class="profile" src="{{ post.poster_url }}" alt="Poster do post {{ post.name}}">
    <ul>
        <li>Nome: {{ post.name }}</li>
        <li>Review: {{ post.text }} </li>
        {% if post.category_set.all %}
            Categorias:
            {% for category in post.category_set.all %}

            <li> Categoria:<a href="{% url 'reviews:single' category.id %}" > {{category.name}}</a>
            </li>
            {% endfor %}


        {% endif %}
        <li><a href="{% url 'reviews:update' post.id %}">Editar</a></li>
        <li><a href="{% url 'reviews:delete' post.id %}">Apagar</a></li>
        
    </ul>
    <ul>
        {% if post.comment_set.all %}
            {% for comment in post.comment_set.all reversed %}
                <figure>
                    <blockquote>
                        "{{ comment.text }}"
                    </blockquote>
                    <figcaption>—{{ comment.author }}
                        <p>
                            Data:{{ comment.date }}
                        </p>
                </figure>
            {% endfor %}
        {% else %}
            <p>Ainda não existe nenhum comentário.</p>
        {% endif %}
    </ul>

    <a href="{% url 'reviews:comment' post.pk %}"><button>Crie seu comentário</button></a>


</section>



{% endblock content %}

reviews/templates/reviews/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Reviews sobre a série de jogos</h2>
<section>
    
    <p>Deixe sua opinião! <a href="{% url 'reviews:create' %}">Criar nova postagem</a></p>
</section>
{% if post_list %}
<section>
    {% for post in post_list %}
    <article>
        <a href="{% url 'reviews:detail' post.id %}"><img class="profile" src="{{ post.poster_url }}"
                alt= "Poster do review {{ post.name }}">
                <p>{{ post.name }} </p>
            </a>

                
        
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum resultado.</p>
{% endif %}

{% endblock content %}

reviews/templates/reviews/single.html
{% extends 'base.html' %}

{% block content %}
<h2>Categorias Relacionadas</h2>
<section>
    
    <h3>{{ category.name }} </h3>
    {{ category.desc }}
    
</section>

<section>
    <ul>
    {% for post in category.group.all %}
    <article>
        
        <li><a href="{% url 'reviews:detail' post.id %}">
        {{ post.name }} </a></li>

    </article>
    {% endfor %}
    </ul>
</section>


{% endblock content %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar postagem {{ post.name }}({{ post.text}})</h2>
<form method="POST" action="{% url 'reviews:update' post.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/base.html
{% load static %}

<!DOCTYPE html><html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Final Fantasy
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header>
        

        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8VRv03Sgt38X9D6me1Rn2B_OFcWpI1qfvwQ&usqp=CAU" width="173" height="133" alt="logo">
        <h1>Final Fantasy</h1>
        <nav>
            <ul>
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
                <li><a href="{% url 'themes' %}">Temas</a></li>
                <li><a href="{% url 'reviews:index' %}">Reviews</a></li>
                <li><a href="{% url 'reviews:category' %}">Busca de categorias</a></li>
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
    <footer>
        <p>
            <small>Copyright 2021 Lucas Zago.</small>
        </p>
    </footer>
</body>

</html>

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
    <main>
        
    <h2>Sobre</h2>
    
    

Esta página será dedicada para contar um pouco sobre mim e sobre minha motivação para criar este site.

<p>

</p>
<div class="container">
    <div class="child-1"> 
    <h3>Sobre mim</h3>
    
    <p>Olá! Estou no meu terceiro ano do curso de Engenharia Mecatrônica. 
        Este site é um dos trabalhos que me foram solicitados para o segundo semestre de 2021!
        Como tema do site eu decidi fazer sobre algo que eu goste e por isso acabou sendo este jogo.
        Esta série de jogos criou várias classes mágicas e dentre elas, a que eu mais me identifico é o mago vermelho, mostrado na imagem a seguir
        
        
    </p>
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRocRQCPcZu2u1C3oKIHdL_iyOgYxvLiW3eFw&usqp=CAU">
    
    </div>
    
    <div class="child-2">
    <h3>Sobre como eu passei a gostar tanto destes jogos</h3>
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfRQIdcsmkB0UUuZ5lqgBR4EqOrJAnc0MCEw&usqp=CAU">
    
    <p>
        Eu conseguir pôr minhas mãos em todos os 15 jogos da série principal
        lançados até hoje e o primeiro deles foi o Final Fantasy IV.
         Na época eu ainda não entendia Inglês para poder acompanhar a narrativa, porém por sorte
         consegui encontrar uma versão do jogo traduzida em Português por fãs,
         permitindo que eu compreendesse a história e me envolvesse com a série.
    </p>
    </div>
</div>


    


    

    </main>


{% endblock content %}

staticpages/templates/staticpages/chars.html
{% extends 'base.html' %}
{% block title %}
Temas
{% endblock title %}

{% block content %}

<main>
        
    <h2>Personagens importantes</h2>
    
    <p>O que seria de uma boa história se não fosse seus personagens? Dentre os 15 jogos da linha principal eu estarei listando abaixo o meu TOP 10 melhores personagens da série!</p>
<ol start="10">
<li><strong>Ardyn</strong></li>
</ol>
<p><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJTYn6ppguoQ3jp46-yRLck-E4tVoFSrRuTw&amp;usqp=CAU" alt="alt text"></p>
<p>O último vilão lançado na série até a data na qual foi feita este site. Fizeram um bom trabalho em sua criação, na qual o fizeram um sucessor legítimo dos reis e que teve seu lugar usurpado. Condenado a lutar contra a sua vontade pelos deuses, Ardyn tem seu trágico fim na batalha final contra o jogador.</p>
<ol start="9">
<li><strong>Balthier</strong></li>
</ol>
<p><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKniRHZtdHllm4Qoxxh_l_EGjO3znVc-sYcA&amp;usqp=CAU" alt="alt text"></p>
<p>Famoso pirata dos céus do mundo de Ivalice. Balthier decidiu fugir de casa quando seu pai enlouqueceu enquanto desenvolvia armas de destruição em massa, apenas para ter que voltar a confrontá-lo por um acaso sádico do destino. Balthier cresceu como um rapaz empático, mas que gosta de manter as situações sob seu comando, desempenhando o papel de líder.</p>
<ol start="8">
<li><strong>Cecil</strong></li>
</ol>
<p><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9j4vMdzshwaCxNsHyrvpoZngwJGJvMAKh0A&amp;usqp=CAU" alt="alt text"></p>
<p>A história de Cecil conta o clássico arco de redenção de um paladino. Treinado como um cavalheiro das trevas, Cecil se envergonha de suas ações e é banido de seu reino ao questionar os métodos de seu rei. Em sua jornada ele escala o monte sagrado no qual ele lutou contra sua própria versão distorcida e maligna que representava seus pecados e erros, tornando-se ao final um paladino.</p>
<ol start="7">
<li><strong>Lightning</strong></li>
</ol>
<p><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPTKrKrwQdngV2di1Kvs60OrlRJl8qceazjw&amp;usqp=CAU" alt="alt text"></p>
<p>Uma soldada treinada e muito competente. Lightning tem habilidades acrobáticas incríveis, que permitem grandes vantagens durante combates. No decorrer de sua história ela é amaldiçoada por um ser superior a destruir tudo que ela conhecia, sendo que a tarefa deve ser concluída dentro de um limite de tempo. Em caso de falha, ela se tornaria um monstro incapaz de pensar.</p>
<p>A história de Lightning nos inspira a enfrentar nossos destinos.</p>
<ol start="6">
<li><strong>Aerith</strong></li>
</ol>
<p><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDdevpNHwyDZ4IeLUsof9iL7YFHtiZ2TIiMA&amp;usqp=CAU" alt="alt text"></p>
<p>Aerith era a típica garota bonita e gentil que se vê em várias narrativas de ficção, uma moça doce, gentil e ingênua. Porém, com o remake que fizeram de Final Fantasy VII, Aerith foi retrabalhada para agir de forma mais idenfificável com os jogadores. Ela é uma moça de muito bom humor, dedicada a mudar a história da forma como nós conhecemos.</p>
<ol start="5">
<li><strong>Vivi</strong></li>
</ol>
<p><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQIzm_9t0SoVQoE2SlYr2Voj_cIndgptmw5g&amp;usqp=CAU" alt="alt text"></p>
<p>Basicamente, Vivi é um criança criada artifialmente para ser usada como uma arma de guerra. Diferente dos demais da sua &ldquo;espécie&rdquo;, ele é um protótipo criado com consciência e livre arbítrio que se separou de seus criadores antes que pudesse ser descartado. Apesar de ser uma criança, os escritores lhe deram uma história trágica, na qual ele descobre não ter muito tempo de vida depois de seu nascimento e por isso frequentemente o jogador será exposto a seus pensamentos e crises existenciais.</p>
<ol start="4">
<li><strong>Noctis</strong></li>
</ol>
<p><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1GHfrAQ7tpX0lPsA6oOOBTYCzMlONC_Scvg&amp;usqp=CAU" alt="alt text"></p>
<p>Príncipe da mais nova nação em ruínas do planeta, Noctis começa sua história perdendo sua cidade natal e seus entes queridos. Através do apoio de seus três grandes amigos, ele se fortalece para derrubar o império que conquistou seu lar. Devido a seu sangue real, Noctis é capaz de invocar armas e de se teleportar pelos cenários das batalhas.</p>
<ol start="3">
<li><strong>Kain</strong></li>
</ol>
<p><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFckUQM0Og5aDkbaJ2AZsH2tIchmy_7jxZ6tgmCfqKTDntphRKlIHjE29ov73pGODVRoM&amp;usqp=CAU" alt="alt text"></p>
<p>Kain cresceu sob a sombra de seu melhor amigo. Durante sua vida ele buscou ter destaque e trazer orgulho para seu reino, porém nunca conseguiu superar seu amigo, o qual conquistou o coração da dama pela qual se apaixonou. Kain representa a sensação de não se sentir bom o bastante, de se dedicar e lutar por algo e se sentir derrotado por não conseguir vencer. Tenho certeza que muitos já passaram por isso, mostrando o quão humanos e relacionáveis os personagens de ficção conseguem ser.</p>
<ol start="2">
<li><strong>Yuna</strong></li>
</ol>
<p><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyQ2mvTfZECHSSyCu6cBpOilCAXavvQ3OZqg&amp;usqp=CAU" alt="alt text"></p>
<p>Yuna é uma invocadora determinada a impedir o extermíneo de muitas vidas em um futuro próximo. Ela embarca numa aventura com seus guardiões para conseguir a invocação suprema que retardará o apocalipse mesmo sabendo que custará sua própria vida.</p>
<ol>
<li><strong>Ashe</strong></li>
</ol>
<p><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbJ6NoedSmujVQDufDwyR-bYnUhFyZn8OCtQ&amp;usqp=CAU" alt="alt text"></p>
<p>Diante as adversidades da guerra, a princesa Ashe embarca em uma jornada para conseguir poder. Seus esforços resultam no descobrimento de um fonte de poder capaz de dizimar cidades inteiras em segundos, colocando-a em um dilema ético sobre liberdade, vitória e justiça.</p>
<p>&ldquo;Eu sou simplesmente eu mesma. E eu quero apenas ser livre.&rdquo;</p>


    


    

    </main>


{% endblock content %}

staticpages/templates/staticpages/games.html
{% extends 'base.html' %}
{% block title %}
Temas
{% endblock title %}

{% block content %}

<main>
        
    <h2>Jogos da série</h2>
    
    <p>Sendo uma das maiores franquias de jogos eletrônicos, Final Fantasy tem uma longa história com 15 jogos de sua linha principal sendo lançados desde 1987! Abaixo estarão expostos os icônicos logos de cada um dos principais lançamentos.</p>
<ol>
<li><strong>Final Fantasy I</strong></li>
</ol>
<p><img src="https://www.finalfantasykingdom.net/1psp/logo.jpg" alt="alt text"></p>
<ul>
<li>Possui diversas versões;</li>
<li>Deu início a esta grande franquia;</li>
</ul>
<ol start="2">
<li><strong>Final Fantasy II</strong></li>
</ol>
<p><img src="https://www.finalfantasykingdom.net/2psp/logo.jpg" alt="alt text"></p>
<ul>
<li>Introduziu os famosos chocobos!;</li>
<li>Foi o primeiro a se arriscar a traçar narrativas mais elaboradas;</li>
</ul>
<ol start="3">
<li><strong>Final Fantasy III</strong></li>
</ol>
<p><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5hGDCgTkiI_Z-qe9s-qHEplwWpVCCC7Ko48bBHfKobuHAO2c4HEojSNL8xQyCxEe_ccE&amp;usqp=CAU" alt="alt text"></p>
<ul>
<li>Introduziu o glorioso sistema de clases;</li>
<li>Considerado um dos mais difíceis da série;</li>
</ul>
<ol start="4">
<li><strong>Final Fantasy IV</strong></li>
</ol>
<p><img src="https://www.finalfantasykingdom.net/4psp/ff4logo.png" alt="alt text"></p>
<ul>
<li>O favorito de muitos fãs, fazendo muitos fãs novos com sua história bem desenvolvida e músicas cativantes;</li>
</ul>
<ol start="5">
<li><strong>Final Fantasy V</strong></li>
</ol>
<p><img src="https://www.finalfantasykingdom.net/5/logo.jpg" alt="alt text"></p>
<ul>
<li>Trouxe a melhor versão do sistema de classes;</li>
<li>Possui os chefes mais difíceis da série;</li>
</ul>
<ol start="6">
<li><strong>Final Fantasy VI</strong></li>
</ol>
<p><img src="https://www.finalfantasykingdom.net/6/logo2.jpg" alt="alt text"></p>
<ul>
<li>Discutivelmente o melhor de todos pela sua história, personagens, músicas e sistema de combate;</li>
<li>Aclamado como um dos melhores jogos de todos os tempos;</li>
</ul>
<ol start="7">
<li><strong>Final Fantasy VII</strong></li>
</ol>
<p><img src="https://www.finalfantasykingdom.net/7/logo.jpg" alt="alt text"></p>
<ul>
<li>O mais popular de toda a série;</li>
<li>Aclamado como um dos melhores jogos de todos os tempos;</li>
</ul>
<ol start="8">
<li><strong>Final Fantasy VIII</strong></li>
</ol>
<p><img src="https://www.finalfantasykingdom.net/8/logo.jpg" alt="alt text"></p>
<ul>
<li>Um dos mais controversos, devido a seu sistema de magias;</li>
<li>Grande polarizador entre os fãs;</li>
</ul>
<ol start="9">
<li><strong>Final Fantasy IX</strong></li>
</ol>
<p><img src="https://www.finalfantasykingdom.net/9/logo.jpg" alt="alt text"></p>
<ul>
<li>Um dos mais amados entre os fãs;</li>
<li>Considerado o favorito do próprio criador da franquia;</li>
</ul>
<ol start="10">
<li><strong>Final Fantasy X</strong></li>
</ol>
<p><img src="https://www.finalfantasykingdom.net/10/ffxlogo.gif" alt="alt text"></p>
<ul>
<li>Considerado um dos jogos com melhores gráficos do Playstation 2;</li>
<li>Aclamado como um dos melhores jogos de todos os tempos;</li>
<li>Possui centenas de horas de conteúdo extra para os jogadores;</li>
</ul>
<ol start="11">
<li><strong>Final Fantasy XI</strong></li>
</ol>
<p><img src="https://www.finalfantasykingdom.net/11/ffxilogo.gif" alt="alt text"></p>
<ul>
<li>O primeiro jogo da série feito na forma de multijogador massivo online (ou Massive Multiplayer Online - MMO);</li>
<li>Pessoas de diversos lugares podem se conectar e fazerem suas próprias aventuras em um mundo online;</li>
</ul>
<ol start="12">
<li><strong>Final Fantasy XII</strong></li>
</ol>
<p><img src="https://www.finalfantasykingdom.net/12/logo.gif" alt="alt text"></p>
<ul>
<li>Possui um sistema de combate único;</li>
<li>Um dos menos jogados pela comunidade de fãs;</li>
</ul>
<ol start="13">
<li><strong>Final Fantasy XIII</strong></li>
</ol>
<p><img src="https://www.finalfantasykingdom.net/13/ffxiiilogo.gif" alt="alt text"></p>
<ul>
<li>Um dos mais controversos, devido a forma com a qual sua história é contada;</li>
<li>Tem ótimos gráficos para o Playstation 3;</li>
</ul>
<ol start="14">
<li><strong>Final Fantasy XIV</strong></li>
</ol>
<p><img src="https://www.finalfantasykingdom.net/xiv/xivlogo.gif" alt="alt text"></p>
<ul>
<li>Segundo jogo online de modo multijogador massivo da série;</li>
</ul>
<ol start="15">
<li><strong>Final Fantasy XV</strong></li>
</ol>
<p><img src="https://www.finalfantasykingdom.net/15/15logo1.png" alt="alt text"></p>
<ul>
<li>Primeiro jogo no estilo de &ldquo;mundo aberto&rdquo; da série;</li>
<li>Criticado por ter elementos importantes da história fechados através de conteúdos de download adicionais pagos;</li>
</ul>


    


    

    </main>


{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Final Fantasy
{% endblock title %}

{% block content %}
    <main>
        
    <p>Este é um site criado para que eu possa escrever minhas coisas favoritas sobre a série de jogos Final Fantasy, minha série de jogos favorita!</p>
<p>Neste site, você encontrará</p>
<ul>
<li>Jogos da série</li>
<li>Personagens importantes</li>
<li>Magias</li>
<li>Reviews</li>
</ul>
<p>Para acessar esses tópicos ou saber mais sobre o site, use o menu de navegação no topo da página.</p>


    </main>
{% endblock content %}

   

staticpages/templates/staticpages/themes.html
{% extends 'base.html' %}
{% block title %}

{% endblock title %}

{% block content %}

<main>
        
    <h2>Temas</h2>
    <ul>
        
            <li><a href="{% url 'magic' %}">Magias</a></li>
        
            <li><a href="{% url 'chars' %}">Personagens importantes</a></li>
        
            <li><a href="{% url 'games' %}">Jogos da série</a></li>
        
    </ul>
    
    
    
        </main>


{% endblock content %}